name: flutter_dsfr
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  assets:
   - assets/images/

  fonts:
    - family: Marianne
      fonts:
        - asset: assets/fonts/Marianne-Regular.woff
        - asset: assets/fonts/Marianne-Bold.woff
          weight: 700
    
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.woff
        - asset: assets/fonts/Spectral-ExtraBold.woff
          weight: 500